#!/bin/bash

make -C ${OSH_INFRA_PATH} rabbitmq

helm upgrade --install rabbitmq ${OSH_INFRA_PATH}/rabbitmq \
    --namespace=kupenstack \
    --values=/etc/kupenstack/rabbitmq.yaml

# wait for rabbitmq
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kupenstack

