//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Kupenstack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlanceConfiguration) DeepCopyInto(out *GlanceConfiguration) {
	*out = *in
	out.Replicas = in.Replicas
	out.Conf = in.Conf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlanceConfiguration.
func (in *GlanceConfiguration) DeepCopy() *GlanceConfiguration {
	if in == nil {
		return nil
	}
	out := new(GlanceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlanceReplicas) DeepCopyInto(out *GlanceReplicas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlanceReplicas.
func (in *GlanceReplicas) DeepCopy() *GlanceReplicas {
	if in == nil {
		return nil
	}
	out := new(GlanceReplicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizonConfiguration) DeepCopyInto(out *HorizonConfiguration) {
	*out = *in
	out.Replicas = in.Replicas
	out.Conf = in.Conf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizonConfiguration.
func (in *HorizonConfiguration) DeepCopy() *HorizonConfiguration {
	if in == nil {
		return nil
	}
	out := new(HorizonConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizonReplicas) DeepCopyInto(out *HorizonReplicas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizonReplicas.
func (in *HorizonReplicas) DeepCopy() *HorizonReplicas {
	if in == nil {
		return nil
	}
	out := new(HorizonReplicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneConfiguration) DeepCopyInto(out *KeystoneConfiguration) {
	*out = *in
	out.Replicas = in.Replicas
	out.Conf = in.Conf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneConfiguration.
func (in *KeystoneConfiguration) DeepCopy() *KeystoneConfiguration {
	if in == nil {
		return nil
	}
	out := new(KeystoneConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneReplicas) DeepCopyInto(out *KeystoneReplicas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneReplicas.
func (in *KeystoneReplicas) DeepCopy() *KeystoneReplicas {
	if in == nil {
		return nil
	}
	out := new(KeystoneReplicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronConfiguration) DeepCopyInto(out *NeutronConfiguration) {
	*out = *in
	out.Replicas = in.Replicas
	out.Conf = in.Conf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronConfiguration.
func (in *NeutronConfiguration) DeepCopy() *NeutronConfiguration {
	if in == nil {
		return nil
	}
	out := new(NeutronConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronReplicas) DeepCopyInto(out *NeutronReplicas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronReplicas.
func (in *NeutronReplicas) DeepCopy() *NeutronReplicas {
	if in == nil {
		return nil
	}
	out := new(NeutronReplicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NovaConfiguration) DeepCopyInto(out *NovaConfiguration) {
	*out = *in
	out.Replicas = in.Replicas
	out.Conf = in.Conf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NovaConfiguration.
func (in *NovaConfiguration) DeepCopy() *NovaConfiguration {
	if in == nil {
		return nil
	}
	out := new(NovaConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NovaReplicas) DeepCopyInto(out *NovaReplicas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NovaReplicas.
func (in *NovaReplicas) DeepCopy() *NovaReplicas {
	if in == nil {
		return nil
	}
	out := new(NovaReplicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OccpRef) DeepCopyInto(out *OccpRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OccpRef.
func (in *OccpRef) DeepCopy() *OccpRef {
	if in == nil {
		return nil
	}
	out := new(OccpRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackCloudConfigurationProfile) DeepCopyInto(out *OpenStackCloudConfigurationProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackCloudConfigurationProfile.
func (in *OpenStackCloudConfigurationProfile) DeepCopy() *OpenStackCloudConfigurationProfile {
	if in == nil {
		return nil
	}
	out := new(OpenStackCloudConfigurationProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackCloudConfigurationProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackCloudConfigurationProfileList) DeepCopyInto(out *OpenStackCloudConfigurationProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenStackCloudConfigurationProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackCloudConfigurationProfileList.
func (in *OpenStackCloudConfigurationProfileList) DeepCopy() *OpenStackCloudConfigurationProfileList {
	if in == nil {
		return nil
	}
	out := new(OpenStackCloudConfigurationProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackCloudConfigurationProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackCloudConfigurationProfileSpec) DeepCopyInto(out *OpenStackCloudConfigurationProfileSpec) {
	*out = *in
	out.Keystone = in.Keystone
	out.Horizon = in.Horizon
	out.Glance = in.Glance
	out.Nova = in.Nova
	out.Neutron = in.Neutron
	out.Placement = in.Placement
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackCloudConfigurationProfileSpec.
func (in *OpenStackCloudConfigurationProfileSpec) DeepCopy() *OpenStackCloudConfigurationProfileSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackCloudConfigurationProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenstackNode) DeepCopyInto(out *OpenstackNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenstackNode.
func (in *OpenstackNode) DeepCopy() *OpenstackNode {
	if in == nil {
		return nil
	}
	out := new(OpenstackNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenstackNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenstackNodeList) DeepCopyInto(out *OpenstackNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenstackNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenstackNodeList.
func (in *OpenstackNodeList) DeepCopy() *OpenstackNodeList {
	if in == nil {
		return nil
	}
	out := new(OpenstackNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenstackNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenstackNodeSpec) DeepCopyInto(out *OpenstackNodeSpec) {
	*out = *in
	out.Occp = in.Occp
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenstackNodeSpec.
func (in *OpenstackNodeSpec) DeepCopy() *OpenstackNodeSpec {
	if in == nil {
		return nil
	}
	out := new(OpenstackNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenstackNodeStatus) DeepCopyInto(out *OpenstackNodeStatus) {
	*out = *in
	out.DesiredNodeConfiguration = in.DesiredNodeConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenstackNodeStatus.
func (in *OpenstackNodeStatus) DeepCopy() *OpenstackNodeStatus {
	if in == nil {
		return nil
	}
	out := new(OpenstackNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementConfiguration) DeepCopyInto(out *PlacementConfiguration) {
	*out = *in
	out.Replicas = in.Replicas
	out.Conf = in.Conf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementConfiguration.
func (in *PlacementConfiguration) DeepCopy() *PlacementConfiguration {
	if in == nil {
		return nil
	}
	out := new(PlacementConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementReplicas) DeepCopyInto(out *PlacementReplicas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementReplicas.
func (in *PlacementReplicas) DeepCopy() *PlacementReplicas {
	if in == nil {
		return nil
	}
	out := new(PlacementReplicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValuesFile) DeepCopyInto(out *ValuesFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValuesFile.
func (in *ValuesFile) DeepCopy() *ValuesFile {
	if in == nil {
		return nil
	}
	out := new(ValuesFile)
	in.DeepCopyInto(out)
	return out
}
