#!/bin/bash

make -C ${OSH_INFRA_PATH} memcached

helm upgrade --install memcached ${OSH_INFRA_PATH}/memcached --namespace=kupenstack

# wait for memcached
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kupenstack
