#!/bin/bash

make -C ${OSH_INFRA_PATH} ingress

helm upgrade --install ingress-kube-system ${OSH_INFRA_PATH}/ingress \
  --namespace=kube-system \
  --values=/etc/kupenstack/ingressKubeSystem.yaml

# Wait for pods to get ready
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kube-system

# Verify
helm status ingress-kube-system

# Deploy ingress-openstack
helm upgrade --install ingress-openstack ${OSH_INFRA_PATH}/ingress \
  --namespace=kupenstack \
  --values=/etc/kupenstack/ingressComponent.yaml 

# Wait for pods to get ready
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kupenstack

# Verify
helm status ingress-openstack


