#!/bin/bash

mkdir /etc/kupenstack/creds
mkdir /etc/kupenstack/creds/openstack

authUrl="http://keystone.kupenstack.svc.cluster.local/v3"
username="admin"
password="password"
domain="Default"
tenant="admin"

echo $(echo $authUrl | base64 ) > /etc/kupenstack/creds/openstack/authUrl
echo $(echo $username | base64 ) > /etc/kupenstack/creds/openstack/username
echo $(echo $password | base64 ) > /etc/kupenstack/creds/openstack/password
echo $(echo $domain | base64 ) > /etc/kupenstack/creds/openstack/domain
echo $(echo $tenant | base64 ) > /etc/kupenstack/creds/openstack/tenant

