#!/bin/bash

make -C ${OSH_PATH} keystone

helm upgrade --install keystone ${OSH_PATH}/keystone \
    --namespace=kupenstack \
    --values=/etc/kupenstack/keystone.yaml


# wait for keystone
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kupenstack

