#!/bin/bash


make -C ${OSH_PATH} glance

# create volumes for glance
kubectl apply -f /etc/kupenstack/glance-pv.yaml

# glance
helm upgrade --install glance ${OSH_PATH}/glance \
    --namespace=kupenstack \
    --values=/etc/kupenstack/glance.yaml


# wait for glance
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kupenstack

