#!/bin/bash

OPENSTACK_HELM_ROOT_PATH=/opt/openstack-helm

make -C ${OPENSTACK_HELM_ROOT_PATH} glance

# create volumes for glance
kubectl apply -f /etc/kupenstack/glance-pv.yaml

# glance
helm upgrade --install glance ${OPENSTACK_HELM_ROOT_PATH}/glance \
    --namespace=kupenstack \
    --values=/etc/kupenstack/glance.yaml


# wait for glance
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kupenstack

