#!/bin/bash

OPENSTACK_HELM_ROOT_PATH=/opt/openstack-helm

make -C ${OPENSTACK_HELM_ROOT_PATH} horizon

helm upgrade --install horizon ${OPENSTACK_HELM_ROOT_PATH}/horizon \
    --namespace=kupenstack \
    --values=/etc/kupenstack/horizon.yaml


# wait for horizon
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kupenstack

