#!/bin/bash

make -C ${OSH_PATH} horizon

helm upgrade --install horizon ${OSH_PATH}/horizon \
    --namespace=kupenstack \
    --values=/etc/kupenstack/horizon.yaml


# wait for horizon
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kupenstack

