#!/bin/bash

make -C ${OSH_PATH} neutron

helm upgrade --install neutron ${OSH_PATH}/neutron \
    --namespace=kupenstack \
    --values=/etc/kupenstack/neutron.yaml

# wait for everything
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kupenstack

