#!/bin/bash

make -C ${HELM_CHART_ROOT_PATH} mariadb

helm upgrade --install mariadb ${HELM_CHART_ROOT_PATH}/mariadb \
    --namespace=kupenstack \
    --values=/etc/kupenstack/mariadb.yaml

# wait for mariadb
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kupenstack

