#!/bin/bash

make -C ${OSH_INFRA_PATH} mariadb

helm upgrade --install mariadb ${OSH_INFRA_PATH}/mariadb \
    --namespace=kupenstack \
    --values=/etc/kupenstack/mariadb.yaml

# wait for mariadb
cd /opt/openstack-helm && ./tools/deployment/common/wait-for-pods.sh kupenstack

