#!/bin/bash

case "${OPENSTACK_RELEASE}" in
  "queens")
    DEPLOY_SEPARATE_PLACEMENT="no"
    ;;
  "rocky")
    DEPLOY_SEPARATE_PLACEMENT="no"
    ;;
  "stein")
    DEPLOY_SEPARATE_PLACEMENT="yes"
    ;;
  *)
    DEPLOY_SEPARATE_PLACEMENT="yes"
    ;;
esac

if [[ "${DEPLOY_SEPARATE_PLACEMENT}" == "yes" ]]; then
  OSH_EXTRA_HELM_ARGS_NOVA="--values=${OSH_PATH}/nova/values_overrides/train-disable-nova-placement.yaml"
fi


make -C ${OSH_PATH} nova

helm upgrade --install nova ${OSH_PATH}/nova --namespace=kupenstack \
      --values=/etc/kupenstack/nova.yaml \
      ${OSH_EXTRA_HELM_ARGS_NOVA}


